=== simranjeetsingh7896/Ticket-System/xml/supportTickets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dateofissue" type="xs:string" />
                            <xs:element name="status" type="xs:string" />
                            <xs:element name="subject" type="xs:string" />
                            <xs:element name="supportmessages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="datetime" type="xs:string" />
                                                    <xs:element name="text" type="xs:string" />
                                                </xs:sequence>
                                                <xs:attribute name="userId" type="xs:integer" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                        <xs:attribute name="userId" type="xs:positiveInteger" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== simranjeetsingh7896/Ticket-System/xml/supportTickets.xml
<?xml version="1.0" encoding="UTF-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="supportTickets.xsd">
  <ticket id="103400" userId="007007">
    <dateofissue>2021-06-02T08:31:12</dateofissue>
    <status>resolved</status>
    <subject>Change my password</subject>
    <supportmessages>
      <message userId="007007">
        <datetime>2021-06-10-10:31:12</datetime>
        <text>hello sir/mam</text>
      </message>
    </supportmessages>
  </ticket>
  <ticket id="113410" userId="456123">
    <dateofissue>2021-06-05T09:00:10</dateofissue>
    <status>on-going</status>
    <subject>Date of issue of ticket</subject>
    <supportmessages>
      <message userId="456123">
        <datetime>2021-06-06-08:31:12</datetime>
        <text>i want change my ticket issue date</text>
      </message>
      <message userId="123456">
        <datetime>2021-06-08-09:31:12</datetime>
        <text>Thank you for your patience,i will resolve your problem soon</text>
      </message>
    </supportmessages>
  </ticket>
  <ticket id="115411" userId="456123">
    <dateofissue>2021-06-02T08:31:12</dateofissue>
    <status>resolved</status>
    <subject>Change my username</subject>
    <supportmessages>
      <message userId="456123">
        <datetime>2020-05-30-18:31:12</datetime>
        <text>Kindly issue with username</text>
      </message>
    </supportmessages>
  </ticket>
  <ticket id="110125" userId="456123">
    <dateofissue>2021-04-03T05:31:16</dateofissue>
    <status>on-going</status>
    <subject>Help me</subject>
    <supportmessages>
      <message userId="456123">
        <datetime>2021-04-03T05:31:16</datetime>
        <text>I want to change my ticket number</text>
      </message>
    </supportmessages>
  </ticket>
  <ticket id="181850" userId="456123">
    <dateofissue>2021-04-03T05:32:00</dateofissue>
    <status>on-going</status>
    <subject>Help me again</subject>
    <supportmessages>
      <message userId="456123">
        <datetime>2021-04-03T05:32:00</datetime>
        <text>My site not working</text>
      </message>
    </supportmessages>
  </ticket>
  <ticket id="106664" userId="007007">
    <dateofissue>2021-04-03T14:48:24</dateofissue>
    <status>on-going</status>
    <subject>Broken ticket</subject>
    <supportmessages>
      <message userId="007007">
        <datetime>2021-04-03T14:48:24</datetime>
        <text>I have some issues in my website</text>
      </message>
      <message userId="123456">
        <datetime>2021-04-06-09:31:12</datetime>
        <text>What kind of problem you are facing?</text>
      </message>
    </supportmessages>
  </ticket>
<ticket id="181509" userId="007007"><dateofissue>2021-04-27T00:13:52</dateofissue><status>on-going</status><subject>jghig</subject><supportmessages><message userId="007007"><datetime>2021-04-27T00:13:52</datetime><text>kh</text></message></supportmessages></ticket><ticket id="106807" userId="52622"><dateofissue>2021-05-14T00:06:16</dateofissue><status>on-going</status><subject>help</subject><supportmessages><message userId="52622"><datetime>2021-05-14T00:06:16</datetime><text>wefwsfsfsfsdf</text></message></supportmessages></ticket></tickets>
